### ISSUE TITLE
Cannot use important statement outside of a module.

### ISSUE THREAD

**Issue by chogland** [frassinier/storybook-docs-toc#14]
Getting this when starting storybook. Can you please assist? Storybook still successfully builds but i'd like to resolve this error.

WARN   Failed to load preset: {"name":"C:\\code\\rds-core\\rds-components\\node_modules\\storybook-docs-toc\\dist\\index.js","type":"presets"} on level 1
ERR! C:\code\rds-core\rds-components\node_modules\@storybook\addon-docs\blocks.js:1
ERR! import deprecate from 'util-deprecate';
ERR! ^^^^^^
ERR!
ERR! SyntaxError: Cannot use import statement outside a module
ERR!     at compileFunction (<anonymous>)
ERR!     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1049:27)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
ERR!     at require (internal/modules/cjs/helpers.js:93:18)
ERR!     at Object.<anonymous> (C:\code\rds-core\rds-components\node_modules\storybook-docs-toc\dist\components\DocsContainerHOC.js:10:15)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
ERR!     at require (internal/modules/cjs/helpers.js:93:18)
ERR!     at Object.<anonymous> (C:\code\rds-core\rds-components\node_modules\storybook-docs-toc\dist\index.js:28:48)
ERR!  C:\code\rds-core\rds-components\node_modules\@storybook\addon-docs\blocks.js:1
ERR! import deprecate from 'util-deprecate';
ERR! ^^^^^^
ERR!
ERR! SyntaxError: Cannot use import statement outside a module
ERR!     at compileFunction (<anonymous>)
ERR!     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1049:27)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
ERR!     at require (internal/modules/cjs/helpers.js:93:18)
ERR!     at Object.<anonymous> (C:\code\rds-core\rds-components\node_modules\storybook-docs-toc\dist\components\DocsContainerHOC.js:10:15)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
ERR!     at require (internal/modules/cjs/helpers.js:93:18)
ERR!     at Object.<anonymous> (C:\code\rds-core\rds-components\node_modules\storybook-docs-toc\dist\index.js:28:48)
...
`

**Comment by frassinier** [comment]
Hey @chogland, can you give a try to the v1.6.1 where I fixed that import, please?

**Comment by frassinier** [comment]
Feel free to reopen if the issue is still there
