### ISSUE TITLE
Use the new Framework API?

### ISSUE THREAD

**Issue by jonniebigodes** [frassinier/storybook-docs-toc#26]
Hey @frassinier!
I'm one of the Storybook maintainers. I focus primarily on documentation and community outreach. I'm opening up this issue and letting you know that the Storybook API for building addons is currently being updated to factor in the changes introduced by the upcoming 7.0 release. If you're interested in making the required changes to help the community from benefiting from using your addon, we've prepared an abridged guide for the required changes [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040), and if you have any questions or issues, please reach out to us in the #prerelease channel in our [Discord Server](https://discord.gg/storybook). 

Hope you have a great day!

Stay safe

**Comment by JReinhold** [comment]
Hey @frassinier, just trying to reach out again. If you're interested in upgrading this addon to support Storybook v7, we've written a migration guide for addon authors [here](https://github.com/storybookjs/storybook/blob/norbert/add-addon-migration-guide/MIGRATION.md#specific-instructions-for-addon-creators) and [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040).

Storybook v7.0.0 is out - on the `next` tag for now, but it's still targetable with the `^7.0.0` semver range, so you should be able to develop against it with no dependency issues.

If you have any further questions please reach out to us in the #prerelease channel on our [Discord Server](https://discord.gg/storybook) and we'll happily help you out!

cc @ndelangen

**Comment by frassinier** [comment]
Sure I will guys. Need to find time.

**Comment by ChenReuven** [comment]
@frassinier is there any update? :)

Thanks

**Comment by frassinier** [comment]
Sorry for the delay. 
I close that issue since the table of content is now part of [Storybook 7.1+](https://storybook.js.org/docs/react/writing-docs/autodocs#generate-a-table-of-contents) as an official feature. 

This repository is not necessary anymore.
