### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by R-Bower** [frassinier/storybook-docs-toc#9]
This doesn't seem to work.  The table of contents is being rendered but it won't appear anywhere in the UI.  I've tried on my private storybook as well as this repo (cloned + yarn install + yarn storybook).

**Comment by frassinier** [comment]
I've published a demo [here](https://frassinier.github.io/storybook-docs-toc) as an example, feel free to reopen if needed

**Comment by dimitrieh** [comment]
@frassinier I was looking for a visual/demo of the plugin. You should consider featuring this on the readme 😉
